name: anns
channels:
  - conda-forge
  - defaults
  - pytorch-nightly
dependencies:
  - python==3.11.9
  - pip==24.3.1
  - black==24.10.0
  - isort==5.13.2
  - jupyter==1.1.1
  - mypy==1.15.0
  - ruff==0.8.2
  - datasets==3.3.2
  - einops==0.8.0
  - ipympl==0.9.4
  - keras-core==0.1.7
  - matplotlib==3.9.3
  - nose==1.3.7
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.6.0
  - scipy==1.14.1
  - seaborn==0.13.2
  - tqdm==4.67.1
  - transformers==4.49.0
  - pip:
      - graphviz==0.20.3
      - gym==0.26.2
      - tensorflow-addons==0.23.0
      - tensorflow-probability==0.25.0
      - tf-keras==2.18.0
      - torch==2.5.1 --extra-index-url https://download.pytorch.org/whl/nightly/cpu
      - torchaudio==2.5.1
      - torchvision==0.20.1
